### ISSUE TITLE
User Julien hardcoded on vagrant image

### ISSUE THREAD

**Issue by ningod** [jhipster/jhipster-devbox#38] opened 2016-05-09 09:00 UTC
Using the quickstart installation procedure on windows:

`Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file /Users/julien/workspace/jhipster-devbox/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)`

**Comment by jdubois** [comment] 2016-05-09 09:51
I do get an error message after logging, which I just ignored, but I didn't get that "julien" error.
Can you tell me where you saw it exactly?

**Comment by ningod** [comment] 2016-05-09 10:10
i followed the quick installation, my steps:

```
C:\Users\myuser\devel>mkdir vagrant-jhipster

C:\Users\myuser\devel>cd vagrant-jhipster

C:\Users\myuser\devel\vagrant-jhipster>vagrant init jhipster/jhipster-devbox
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.


C:\Users\myuser\devel\vagrant-jhipster>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'jhipster/jhipster-devbox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Setting the name of the VM: vagrant-jhipster_default_1462788320313_26756
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3b887ed6-ac50-4bff-92b7-a7ddb404b5c0", "--type", "headless"]

Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file /Users/julien/workspace/jhipster-devbox/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

C:\Users\myuser\devel\vagrant-jhipster>
```

**Comment by wpfeiffe** [comment] 2016-05-09 10:55
I'm getting the same exact error. On OS X 10.11.14 with latest Vagrant:

```
vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1b819cd4-4313-4bc1-88d6-921bbba3109c", "--type", "headless"]

Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /Users/julien/workspace/jhipster-devbox/ubuntu-xenial-16.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole


```

**Comment by jdubois** [comment] 2016-05-09 11:40
OK thanks, I'm going to have a look ASAP

**Comment by jdubois** [comment] 2016-05-09 12:38
Thanks a lot @ningod @wpfeiffe there is indeed an error -> it's a bit complex to test (as this depends on the OS), but I'll push up a new version "3.2.1.1" to Atlas, trying to correct it. Will you be able to test?
I'll post another comment when it's ready (depends on my network connection).

**Comment by wpfeiffe** [comment] 2016-05-09 12:55
I'll test when I see it the ready comment.

**Comment by jdubois** [comment] 2016-05-09 14:07
And it's alive at https://atlas.hashicorp.com/jhipster/boxes/jhipster-devbox/versions/3.2.1.1

-> thanks for testing!

**Comment by wpfeiffe** [comment] 2016-05-09 14:11
Pulling it down now.  My network is slow so it'll be about an hour before I can report results.

**Comment by ningod** [comment] 2016-05-09 14:31
The problem is not solved.

I did 
`vagrant box update `
and then 
`vagrant up `
but the bug is still there


```
C:\Users\myuser\devel\vagrant-jhipster>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'jhipster/jhipster-devbox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: A newer version of the box 'jhipster/jhipster-devbox' is available! You currently
==> default: have version '3.2.1'. The latest is version '3.2.1.1'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: vagrant-jhipster_default_1462803309552_38822
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "4503fc1d-9979-4605-a2fa-9ac4da80e601", "--type", "headless"]

Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file /Users/julien/workspace/jhipster-devbox/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

C:\Users\myuser\devel\vagrant-jhipster>vagrant box update
==> default: Checking for updates to 'jhipster/jhipster-devbox'
    default: Latest installed version: 3.2.1
    default: Version constraints:
    default: Provider: virtualbox
==> default: Updating 'jhipster/jhipster-devbox' with provider 'virtualbox' from version
==> default: '3.2.1' to '3.2.1.1'...
==> default: Loading metadata for box 'https://atlas.hashicorp.com/jhipster/jhipster-devbox'
==> default: Adding box 'jhipster/jhipster-devbox' (v3.2.1.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/jhipster/boxes/jhipster-devbox/versions/3.2.1.1/providers/virtualbox.box
    default: Progress: 100% (Rate: 5608k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'jhipster/jhipster-devbox' (v3.2.1.1) for 'virtualbox'!

C:\Users\myuser\devel\vagrant-jhipster>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "4503fc1d-9979-4605-a2fa-9ac4da80e601", "--type", "headless"]

Stderr: VBoxManage.exe: error: RawFile#0 failed to create the raw output file /Users/julien/workspace/jhipster-devbox/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

C:\Users\myuser\devel\vagrant-jhipster>
```

**Comment by jdubois** [comment] 2016-05-09 14:38
Thanks for testing -> can you totally delete your box and try again? I think that if you don't do it, you still run the older box you created with "vagrant up".
I'm not sure the error is solved, but you shouldn't have the "julien" part -> I'm pretty sure this part was removed

**Comment by wpfeiffe** [comment] 2016-05-09 14:54
It looks like I get past the original error and get stuck in the authentication loop:
`vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...`

**Comment by jdubois** [comment] 2016-05-09 14:56
Good news already! It might take some time to startup, and during that time it's trying to reconnect... Did you wait a few minutes?

**Comment by wpfeiffe** [comment] 2016-05-09 16:18
The box started and I opened the virtualbox window and logged in as jhipster.  I expected to have to do this, however, I did not expect the command to spin on auth failure.  I will try again.  Ok command continues to fail on auth and eventually times out.  The box DOES start though.

**Comment by ningod** [comment] 2016-05-09 16:38
After totally delete my box... new problem :-(
```
C:\Users\myuser\devel\vagrant-jhipster>vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'jhipster/jhipster-devbox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Setting the name of the VM: vagrant-jhipster_default_1462811011577_85820
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

C:\Users\myuser\devel\vagrant-jhipster>
```

**Comment by jdubois** [comment] 2016-05-09 16:48
At least the original problem is solved :-)
There is a first error message telling about port 22 being already used,
maybe that's the cause of the issue?
And in the VM console, do you see any error messages?
Le 9 mai 2016 6:38 PM, "Stefano Vetrini" <notifications@github.com> a
écrit :

After totally delete my box... new problem :-(

C:\Users\myuser\devel\vagrant-jhipster>vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'jhipster/jhipster-devbox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'jhipster/jhipster-devbox' is up to date...
==> default: Setting the name of the VM:
vagrant-jhipster_default_1462811011577_85820
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

C:\Users\myuser\devel\vagrant-jhipster>

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/jhipster/jhipster-devbox/issues/38#issuecomment-217917885>

**Comment by cbornet** [comment] 2016-05-10 09:23
@ningod do you have another vagrant machine already started ? I had the same issue in that case.

**Comment by cbornet** [comment] 2016-05-10 09:45
Actually I have the same issue. I think it's because vagrant tries to use the user vagrant and the insecure_key and those aren't installed.
Otherwise the box boots OK. It's just that you can't run provisionning scripts (which I'm doing btw).

**Comment by cbornet** [comment] 2016-05-10 10:27
I had to add
```ruby
	config.ssh.username = "jhipster"
	config.ssh.password = "jhipster"
```
and set jhipster as a passwordless sudoer
```
sudo visudo
...
jhipster ALL=(ALL) NOPASSWD:ALL
```
to make it work.

**Comment by jdubois** [comment] 2016-05-10 11:48
Hi, at least the first issue seems solved. But I don't understand all the other issues here -> @cbornet do you need this to do re-provisionning of the box? And the passwordless part isn't scripted, so I guess you do it afterwards?

**Comment by cbornet** [comment] 2016-05-10 12:01
Yes, I started the box, provisionning failed. Then I logged-in as jhipster, configured the jhipster passwordless sudo from a terminal, then restarted the box and provisionning succeeded using user jhipster.
Note that commands such as ```vagrant halt``` will also fail if ssh+sudo is not possible.

The initial issue is that the ubuntu/xenial64 box doesn't have the vagrant user.
The requirements for a base box for the vagrant user are [here](https://www.vagrantup.com/docs/boxes/base.html) (insecure keypair, root password, passwordless sudo, ...). With ```config.ssh``` we can configure vagrant to use jhipster user instead but IMO it would be cleaner to have a correclty configured vagrant user.

**Comment by cbornet** [comment] 2016-05-10 12:04
I guess to script that, you could do:
```
echo "jhipster ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
```
The visudo command is just a utility to verify the integrity of the file before saving.

**Comment by jdubois** [comment] 2016-05-10 12:07
@cbornet yes I know for `visudo`, it's just that I see you did it manually and not scripted it, so I'm wondering what I should do here
when you say "provisionning failed", you mean you did build the image yourself, and not downloaded it from Atlas?

**Comment by cbornet** [comment] 2016-05-10 12:15
I downloaded the jhipster-devbox 3.2.1.1 from Atlas, then up'ed it with a personal provisionning script set in my Vagrantfile.

Also, better command:
```
echo "jhipster ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jhipster
```

**Comment by jdubois** [comment] 2016-05-10 12:17
OK, but was the original image working?
I'll test your "jhipster" user method, as it would cleaner than to have the current useless ubuntu user

**Comment by ningod** [comment] 2016-05-10 12:28
@cbornet Yes I had another VM running, but the log said that was not a problem ( port 2200 was used instead )

I tried to access to VM by Virtualbox Interface after vagrant up (and its failure ) and it all works ( except for the default french language, that i don't understand :-( )

**Comment by jdubois** [comment] 2016-05-10 12:31
OK so this confirms the original ticket is fixed.
@ningod you had an original "French" language?

**Comment by jdubois** [comment] 2016-05-10 12:32
I'm closing this as the original issue is fixed, but it seems we still have some other problems

**Closed by jdubois** 2016-05-10 12:32 UTC

**Comment by cbornet** [comment] 2016-05-10 12:55
I think this should create the vagrant user correclty
```
useradd vagrant --password wthgG9Dxlk13E --home /home/vagrant --create-home -s /bin/bash
echo "vagrant ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vagrant
mkdir -p /home/vagrant/.ssh
wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys
chmod 0700 /home/vagrant/.ssh
chmod 0600 /home/vagrant/.ssh/authorized_keys
chown -R vagrant /home/vagrant/.ssh
```
I don't have time to test right now...

**Comment by cbornet** [comment] 2016-05-10 13:51
So I could make the vagrant user work with the config above.
The thing is it's configured with the insecure_keypair whereas the box was packaged with a replaced keypair (the one for ubuntu user)
So I removed vagrant_private_key and commented config.ssh.private_key_path in Vagrantfile in ```~\.vagrant.d\boxes\jhipster-VAGRANTSLASH-jhipster-devbox\3.2.1.1\virtualbox``` and it worked.

@jdubois If you decide to create the vagrant user, be sure to set config.ssh.insert_key = false in the Vagrantfile.
