### ISSUE TITLE
webdriver-manager is requiring root rights

### ISSUE THREAD

**Issue by r3dlin3** [jhipster/jhipster-devbox#21] opened 2015-12-28 16:29 UTC
When executing `webdriver-manager update` command (automatically executed by `mvn`), it does not have the necessary rights to write to `/usr/lib/nodes_module`.
If I execute as root the update command, it works. But when I execute again mvn, even if no driver has to be updated, it tries a `chmod`, resulting in a failure.
Execute `mvn` as root fails also on `bower`.

I following this guides so I am able to install globally npm-based commands:
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

I would recommand such configuration to prevent issues

**Comment by jdubois** [comment] 2015-12-29 13:22
I just tried with the latest v2.26.1 devbox version, with a project having all default options.

- no problem running `mvn`
- I don't know this `webdriver-manager` but it looks like it's for testing, so I also ran `mvn test` but I also didn't have any issue

So I understand the type of issue you have here, but I can't reproduce it, so I have to close this (unless you give more information, in which case I will re-open it, of course!)

The tip you give looks also very interesting (ping @pascalgrimaud @mraible  ) as this means we could have some kind of "npm cache" like we have for Maven -> I will open up a separate ticket to have a look at this on our main project

**Closed** 2015-12-29 13:23 UTC

**Comment by pascalgrimaud** [comment] 2015-12-29 14:00
@r3dlin3 : try to use this command `sudo chown -R vagrant /usr/lib/node_modules`
As you are root in this VM, you ll be able to be the real owner of this directory

If I remember well, webdriver-manager is used with protractor

**Comment by jdubois** [comment] 2015-12-29 17:07
@pascalgrimaud that would explain why I didn't know about it -> @r3dlin3 can you confirm this?
